exports.queryList = {
    GET_STORES_LIST_QUERY:
        "SELECT store_id, store_name, store_code, created_on, created_by, address FROM books_mangement_system.store",
    ADD_STORE_QUERY:
        "INSERT INTO books_mangement_system.STORE (STORE_NAME, STORE_CODE, CREATED_ON , CREATED_BY , ADDRESS) VALUES($1, $2, $3, $4, $5)",
    DELETE_STORE_QUERY:
        "DELETE FROM books_mangement_system.STORE WHERE STORE_ID = $1",
    EDIT_STORE_QUERY:
        "UPDATE books_mangement_system.STORE SET STORE_NAME = $1, ADDRESS = $2 WHERE STORE_ID = $3",
    GET_BOOKS_LIST_QUERY:
        "SELECT BOOK_ID, BOOK_TITLE, BOOK_DESCRIPTION, BOOK_AUTHOR, BOOK_PUPLISHER, BOOK_PAGES, STORE_CODE, CREATED_ON, CREATED_BY, BOOK_ISBN FROM BOOKS_MANGEMENT_SYSTEM.BOOK;",
    ADD_BOOK_QUERY:
        "INSERT INTO BOOKS_MANGEMENT_SYSTEM.BOOK (BOOK_TITLE, BOOK_DESCRIPTION, BOOK_AUTHOR, BOOK_PUPLISHER, BOOK_PAGES, STORE_CODE, CREATED_ON, CREATED_BY, BOOK_ISBN) VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9)",
};
